new gui app initital

diff --git a/src/sudo b/src/sudo
--- a/src/sudo
+++ b/src/sudo
@@ -1,8 +1,8 @@
 #!/bin/sh
 VERSION="0.6"
 
-function print_info(){
-	echo "
+print_info() {
+	cat <<EOF
 Gsudo $VERSION | Copyright (c) 2020 AXON | supreme-gamers.com
 The android_x86 tty actions are done over the \`root:shell' usergroup.
 Which causes some executable binaries to be working in a wrong manner even while it's still the root user partially.
@@ -21,30 +21,25 @@ Example: ${0##*/} mkdir /data/new
 
 Gsudo is a part of GearLock
 For more information & bugreports visit https://supreme-gamers.com/gearlock
-	"
+EOF
+	exit 0
 }
 
 case "$1" in
-	-h|--help)
-		print_info
-		;;
-	-v|--version)
-		echo "$VERSION"
-		;;
-	*)
-		# Ensure we have su binary
-		! command -v su 1>/dev/null && {
-			echo "Error: su binary is not present" && exit 1
-		}
-		suargs=$(printf '%q ' "$@")
-		if test -n "${suargs}"; then
-			if test -z "$RECOVERY" && test -z "$GSUDO"; then
-				GSUDO="yes" su -c "PATH=$PATH; TERM=$TERM; bash -c \"$suargs\""
-			else
-				export GSUDO="yes" && "$@"
-			fi
-		else
-			print_info
-		fi
+-h | --help) print_info ;;
+-v | --version) echo "$VERSION" ;;
+*)
+	# Ensure we have su binary
+	! command -v su 1>/dev/null && {
+		echo "Error: su binary is not present" && exit 1
+	}
+	suargs=$(printf '%q ' "$@")
+	[ -z "${suargs}" ] && print_info
+
+	if test -z "$RECOVERY" && test -z "$GSUDO"; then
+		GSUDO="yes" su -c "PATH=$PATH; TERM=$TERM; bash -c \"$suargs\""
+	else
+		export GSUDO="yes" && "$@"
+	fi
 	;;
 esac
diff --git a/src/usr/local/bin/gearlock-cli b/src/usr/local/bin/gearlock-cli
--- a/src/usr/local/bin/gearlock-cli
+++ b/src/usr/local/bin/gearlock-cli
@@ -2,8 +2,8 @@
 EXEC_NAME="${0##*/}"
 argv="$1"
 shift
-function printUsage(){
-	echo -e "
+printUsage() {
+	cat <<EOF
 GearLock-Cli can be used to run anything while hooking gearlock core.
 It scans for your specified input in the following places:
     '/gearlock/core/'your-input', '\$PATH' or 'specified-path-for-executable'.
@@ -16,10 +16,10 @@ Examples:   gsudo $EXEC_NAME main.src/4
             gsudo $EXEC_NAME ./my-script.sh
             
 Note: You have to call \`gearlock-cli\` through \`gsudo\` to ensure optimal environment for GearLock runtime.
-"
+EOF
 }
 
-function loadCore(){
+loadCore() {
 	IT="${DEFAULT_THEME:="metro"}" && {
 		source "/gearlock/bin/fetch" || exit
 		source "/gearlock/bin/fetch.in" || exit
@@ -28,25 +28,18 @@ function loadCore(){
 }
 
 case "$argv" in
-	-v|--version)
-		cat /gearlock/core/version
-	;;
-	-h|--help)
-		printUsage
-	;;
-	*) 
-		if [ -z "$argv" ]; then
-			echo -e "$EXEC_NAME: no input provided, try \`$EXEC_NAME --help\`"
-		elif [ -n "$argv" ]; then
-			test -z "$GSUDO" && echo "$EXEC_NAME: Please run as \`gsudo $EXEC_NAME $argv $@\`" && exit 1
-			if [ -e "/gearlock/core/$argv" ]; then
-				loadCore && "/gearlock/core/$argv" "$@"
-			elif b="$(which "$argv")"; then
-				test ! -x "$b" && echo "$EXEC_NAME: Execution permission not granted for $argv" && exit 1
-				loadCore && "$b" "$@"
-			else
-				echo "$EXEC_NAME: $argv not found"
-			fi
-		fi
+-v | --version) cat /gearlock/core/version ;;
+-h | --help) printUsage ;;
+*)
+	[ -z "$argv" ] && echo -e "$EXEC_NAME: no input provided, try \`$EXEC_NAME --help\`" && exit 1
+	[ -z "$GSUDO" ] && echo "$EXEC_NAME: Please run as \`gsudo $EXEC_NAME $argv $*\`" && exit 1
+	if [ -e "/gearlock/core/$argv" ]; then
+		loadCore && "/gearlock/core/$argv" "$@"
+	elif b="$(which "$argv")"; then
+		test ! -x "$b" && echo "$EXEC_NAME: Execution permission not granted for $argv" && exit 1
+		loadCore && "$b" "$@"
+	else
+		echo "$EXEC_NAME: $argv not found"
+	fi
 	;;
 esac
diff --git a/src/usr/share/gearlock/core/gdev.src/1 b/src/usr/share/gearlock/core/gdev.src/1
--- a/src/usr/share/gearlock/core/gdev.src/1
+++ b/src/usr/share/gearlock/core/gdev.src/1
@@ -7,11 +7,11 @@ if test -z "$GEARLOCK_VER"; then
 		WORKDIR="$BD/workdir" \
 		GCOMM="gearlock" \
 		GRLOAD="$BD/gearload" \
-		PS3="$(echo -e "\nEnter a number >> ")" 
+		PS3="$(echo -e "\nEnter a number >> ")"
 	mkdir -p "$GTMP" "$GRLOAD"
 	PATH="$BD/bin:$PATH"
-	! chmod -R 777 "$BD/bin" > /dev/null 2>&1 \
-		&& echo "Failed to get execution permissions on 'bin/garc'" && exit 1
+	! chmod -R 777 "$BD/bin" >/dev/null 2>&1 &&
+		echo "Failed to get execution permissions on 'bin/garc'" && exit 1
 	test -z "$NO_PULL" && SHA="$(sha256sum "$0")" && {
 		echo -e '+ Running git pull: \c' && git pull
 		echo
@@ -19,18 +19,17 @@ if test -z "$GEARLOCK_VER"; then
 	}
 fi
 
-
-function main(){
+main() {
 	echo -e '\n+ Checking for internet access ...' && {
-		! curl --output /dev/null --silent --fail -r 0-0 "https://www.google.com" \
-			&& echo -e "Your internet is down." && exit 1
+		! curl --output /dev/null --silent --fail -r 0-0 "https://www.google.com" &&
+			echo -e "Your internet is down." && exit 1
 	}
-		
+
 	echo -e "\n+ Downloading $1 ..." && {
-		! curl -LkSs "https://api.github.com/repos/AXIM0S/${1}/tarball" -o "$GTMP/${1}.tar.gz" \
-			&& echo -e "Failed to download skeleton package, please try again" && exit 1
+		! curl -LkSs "https://api.github.com/repos/AXIM0S/${1}/tarball" -o "$GTMP/${1}.tar.gz" &&
+			echo -e "Failed to download skeleton package, please try again" && exit 1
 	}
-	
+
 	echo -e "\n+ Setting up $1 ...\n" && {
 		test -e "$WORKDIR" && read -rn1 -p ' -- [!!!] Warning, workdir already exists, remove ? [Y/n] ' c && test "${c,,}" == "y" && rm -r "$WORKDIR" && echo
 		mkdir -p "$WORKDIR"
@@ -38,14 +37,14 @@ function main(){
 		find "$WORKDIR" -name ".keep" -exec rm {} +
 		chmod -R 755 "$WORKDIR"
 	}
-	
+
 	echo -e "\n+ Browse to $WORKDIR
 \n+ If you havent read the documentation yet then visit https://supreme-gamers.com/gearlock"
 	test -z "$ME" && echo -e "\n\n++ Run ./build to make your extension/package once it's ready"
 	:
 }
 
-wizard_run(){
+wizard_run() {
 	echo -e "~ Choose what kind of Custom Package you want to work with ...
 ~ You may select the *kernel/mesa-specific package if you want a pre-configured kernel/mesa installer engine
 ~ You can use the *core-package for building something complex like an ${BGREEN}Extension${RC} or for ${YELLOW}boot-executables${RC} or anything!\n"
@@ -60,9 +59,8 @@ wizard_run(){
 	done
 }
 
-
-show_help(){
-echo -e "
+show_help() {
+	echo -e "
 GearLock Development Kit
 \$ Command Line Options: ./${0##*/} <option>
 
@@ -81,10 +79,10 @@ if test -z "$1"; then
 	wizard_run
 else
 	case "$1" in
-		--gearlock-kernel-pkg) main "${1#--}" ;;
-		--gearlock-mesa-pkg) main "${1#--}" ;;
-		--gearlock-core-pkg) main "${1#--}" ;;
-		--help|-h) show_help ;;
-		*) echo -e "${0##*/}: unknown option: "$* && show_help ;;
+	--gearlock-kernel-pkg) main "${1#--}" ;;
+	--gearlock-mesa-pkg) main "${1#--}" ;;
+	--gearlock-core-pkg) main "${1#--}" ;;
+	--help | -h) show_help ;;
+	*) echo -e "${0##*/}: unknown option: "$* && show_help ;;
 	esac
 fi
diff --git a/src/usr/share/gearlock/core/main.src/3 b/src/usr/share/gearlock/core/main.src/3
--- a/src/usr/share/gearlock/core/main.src/3
+++ b/src/usr/share/gearlock/core/main.src/3
@@ -1,5 +1,5 @@
 # Define Functions
-do_sync(){
+do_sync() {
     echo -e "\n+ ${_syncing_drive_} ..."
     (
         mount -o rw,remount,atime,diratime,relatime "$GRROOT_DIR"
@@ -7,22 +7,23 @@ do_sync(){
         sync "${GRROOT}/"*
         sync "${GRROOT}/system.img"
         mount -o rw,remount,noatime "$GRROOT_DIR"
-    )>/dev/null 2>&1
-    mount | grep "$GRROOT_DIR" | grep -q "type ext" && export FIXFS=0 && sleep 7 && fixfs;:;
+    ) >/dev/null 2>&1
+    mount | grep "$GRROOT_DIR" | grep -q "type ext" && export FIXFS=0 && sleep 7 && fixfs
+    :
 }
 
-handleError(){ if [ $? != 0 ]; then echo -e "\n++++ Error: $1" && exit "${2:-1}"; fi; }
+handleError() { sleep 3 && echo -e "\n++++ Error: $1" && exit "${2:-1}"; }
 
-extend_system_img(){ "$CORE/extimg" "system.img" "$((SC_SIZE + 10))"; }
+extend_system_img() { "$CORE/extimg" "system.img" "$((SC_SIZE + 10))"; }
 
-decom_sys(){
+decom_sys() {
     echo -e "\n+ ${_supercharge_decompress_img_info_} ..."
     gclone /system "${GRROOT}/"
     chmod 755 "${GRROOT}"/system
     (
         # Free loop devices to avoid read errors.
         for loopDev in $(mount | grep "^/dev/loop" | awk '{print $1}' | tac); do mount 2>/dev/null | grep -q "^$loopDev" && umount -d "$loopDev"; done
-        
+
         # unMount img mountpoints
         for mp in /system /data /android/system /android/data /sfs; do mountpoint -q $mp && umount $mp; done
     )
@@ -31,11 +32,13 @@ decom_sys(){
     echo -e "\n+ ${_decompression_successful_} ... !"
 }
 
-
-if test -z "$RECOVERY"; then sleep 3 && false; handleError "Only available in RECOVERY-MODE ..."; fi
-if test -z "$ANDROID_VER"; then sleep 3 && false; handleError "Failed to get ANDROID_VERSION information ..."; fi
+[ "$RECOVERY" ] || handleError "Only available in RECOVERY-MODE ..."
+[ "$ANDROID_VER" ] || handleError "Failed to get ANDROID_VERSION information ..."
 # Check if mountpoints are writable
-for mp in "$GRROOT"/*; do ! touch -c "$mp">/dev/null 2>&1 && echo -e "[!!!] ${mp##*/} is not writable." && { greboot; exit 1; }; done
+for mp in "$GRROOT"/*; do ! touch -c "$mp" >/dev/null 2>&1 && echo -e "[!!!] ${mp##*/} is not writable." && {
+    greboot
+    exit 1
+}; done
 # Check for running progs in volatile mountpoints
 lsof_dump="$(lsof 2>/dev/null)"
 for mp in /mnt /gearlock/gearroot /android /data /system; do
@@ -45,22 +48,22 @@ done
 echo -e "\n\n+ ${_checking_system_} ..."
 
 # Main
-if ls "$OROOT/system."*>/dev/null 2>&1 && test "$(stat -L --printf="%s" "$OROOT/system."*)" -lt "$((SC_SIZE * 1048576))"; then
-    
-    if [[ "$ANDROID_VER" =~ [4-7] ]]; then
-        
-        # ext
-        if mount | grep "$GRROOT_DIR" | grep -q "type ext"; then
-            decom_sys
-        else
-            # fuseblk
-            extend_system_img
-        fi
-        
+if ! ls "$OROOT/system."* >/dev/null 2>&1 || ! test "$(stat -L --printf="%s" "$OROOT/system."*)" -lt "$((SC_SIZE * 1048576))"; then
+    echo -e "\n+ ${_system_is_supercharged_}"
+    sleep 4
+    exit 1
+fi
+
+if [[ "$ANDROID_VER" =~ [4-7] ]]; then
+
+    # ext
+    if mount | grep "$GRROOT_DIR" | grep -q "type ext"; then
+        decom_sys
     else
+        # fuseblk
         extend_system_img
     fi
-    
+
 else
-    echo -e "\n+ ${_system_is_supercharged_}" && sleep 4
+    extend_system_img
 fi
